name: Build Automation ðŸŽ®

on: push

jobs:
  iosBuildAndShip:
    if: startsWith(github.event.head_commit.message, 'build:')
    name: iOS Build & TestFlight âœ¨
    runs-on: self-hosted   # (gerekirse kendi labelâ€™Ä±nÄ± da ekle: [self-hosted, macmini-01])
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Prepare LFS cache
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-iOS
          restore-keys: |
            Library-

      - name: Build with Unity (iOS)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          # unityVersion / projectPath gerekiyorsa ekle

      - name: Debug â€” list build
        run: ls -laR build/iOS

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install fastlane
        run: gem install fastlane

      - name: Fastlane beta (TestFlight)
        env:
          APP_STORE_CONNECT_API_KEY_PATH: /Users/cagilfirat/Documents/Projects
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          PROJECT_PATH: build/iOS/Unity-iPhone.xcodeproj
          SCHEME: Unity-iPhone
        run: fastlane ios beta
